### ISSUE TITLE
Azure DevOps Bot fires multiple events creating the same message to post twice

### ISSUE THREAD

**Issue by danhellem** [danhellem/github-actions-pr-is-linked-to-work-item#88]
Because of how the Azure Boards Bot works, it triggers the action multiple times when creating the link. The events fire at the same time. This can generate multiple messages. We need to be checking to see if the check is already running and then delay. This should solve the problem.

**Comment by WillEllis** [comment]
Hey @danhellem. 
I'm seeing this issue on PR open as we have the Azure Boards bot installed. 
It triggers on opened, fails, and within seconds of open the Azure Boards bot edits the PR so the action runs again and succeeds.
However to work around this I modified your example workflow file to not trigger on opened: 
```
on: # rebuild any PRs for main branch changes
  pull_request:
    types: [reopened, edited]
    branches:
      - main 
```

My thinking here is that with the Azure Boards bot installed any opened PR won't be correct until the bot edits the PR. This seems to work ok, however maybe I'm missing something.

If you think thats sound logic then maybe a modification of the example in the readme is enough to work around this bug in general.
